In [386]:
import pandas as pd 
import numpy as np

In [387]:
spotify = pd.read_csv("Spotify_Music_ Data_Analysis_ using_Pandas.csv")

##### time_signature - It shows how many beats are present in one musical bar/measure.
##### track_popularity - How popular the song is on Spotify.
##### speechiness - How much spoken words or talking is present in the song. range ( 0 - 1 ) in between.
##### danceability - How suitable the song is for dancing. range ( 0 - 1 ) in between.
##### playlist_name - The name of the playlist in which the song is included.
##### track_artist - The name of the artist/singer/band who created the song.
##### duration_ms - The total length of the song in milliseconds.
##### energy - How intense, powerful, or active the song feels. range ( 0 - 1 ) in between.
##### playlist_genre - The main music genre/category of the playlist.
##### playlist_subgenre - A more specific category inside the main genre.
##### track_name - The name/title of the song.
##### mode - The emotional musical mode of the song. range ( 0 - 1 ) 1 = happy, 0 = sad
##### track_album_release_date - The release date of the album or song.
##### instrumentalness - How likely the song is instrumental (without vocals/singing). range ( 0 - 1) 0 = normal singing, 1 = fewer vocals,     
#####                    more  instrumental.
##### valence - The emotional positivity or happiness level of a song. range ( 0 - 1 ) 0 = sad, 1 = happy
##### tempo - The speed of the song.
##### loudness - How loud the song is overall.
##### acousticness - How much the song sounds acoustic/natural. range ( 0 - 1 ) 0 = electrical, 1 = natural
##### liveness - How much the song sounds like a live performance. range ( 0 - 1 )
##### track_album_name - The name of the album in which the song was released.

# Spotify Music Data Analysis using Pandas

## Project Objective

The objective of this project is to analyze Spotify music data using Pandas to understand patterns related to song popularity, genres, artists, and audio features.

## Dataset Understanding

The dataset contains Spotify track information along with multiple audio features and playlist details.

Main columns in the dataset include:
- Track name
- Artist name
- Album name
- Genre and subgenre
- Track popularity
- Danceability
- Energy
- Loudness
- Speechiness
- Acousticness
- Liveness
- Valence
- Tempo

These features help analyze music characteristics, popularity trends, and listener behavior.

## Data Cleaning

The dataset was cleaned before analysis to improve consistency and data quality.

Cleaning steps performed:
- Removed unnecessary columns such as IDs and API links
- Checked missing values
- Removed null values
- Checked duplicate rows
- Converted release date into datetime datatype
- Verified numeric column ranges

In [388]:
#   Remove unnecassary columns
spotify.drop(columns=['track_href','track_album_id','playlist_id','track_id','analysis_url','id','uri','type','key'], inplace=True)

In [420]:
spotify[spotify['speechiness'].isnull()]        # drop na one row from speechiness
spotify.dropna(inplace=True)

In [421]:
spotify.head()

,time_signature,track_popularity,speechiness,danceability,playlist_name,artist_name,duration_ms,energy,playlist_genre,playlist_subgenre,track_name,mode,track_album_release_date,instrumentalness,valence,tempo,loudness,acousticness,liveness,track_album_name
0,4.0,23,0.0393,0.636,Rock Classics,Creedence Clearwater Revival,138053.0,0.746,rock,classic,Fortunate Son,1.0,2005-12-14,0.290000,0.432,132.310,-3.785,0.0648,0.1730,The Long Road Home - The Ultimate John Fogerty...
1,4.0,53,0.0317,0.572,Rock Classics,Van Halen,241600.0,0.835,rock,classic,Jump - 2015 Remaster,1.0,2015-03-27,0.000377,0.795,129.981,-6.219,0.1710,0.0702,The Collection
2,4.0,55,0.0454,0.591,Rock Classics,Stevie Nicks,329413.0,0.804,rock,classic,Edge of Seventeen - 2016 Remaster,1.0,2016-11-04,0.000006,0.658,111.457,-7.299,0.3270,0.0818,Bella Donna (Deluxe Edition)
3,4.0,64,0.1010,0.443,Jazz Classics,"Ella Fitzgerald, Louis Armstrong",185160.0,0.104,jazz,classic,Dream A Little Dream Of Me - Single Version,1.0,2007-05-03,0.000000,0.394,76.474,-17.042,0.9130,0.1910,"Love, Ella"
4,4.0,62,0.0298,0.685,Jazz Classics,Galt MacDermot,205720.0,0.472,jazz,classic,Coffee Cold,0.0,2000-01-01,0.284000,0.475,80.487,-9.691,0.7850,0.2240,Shapes of Rhythm/Woman Is Sweeter

In [459]:
# pd.set_option('display.max_columns', None)      # It shows all the columns if no of columns are higher 

spotify.columns         # columns name

Index(['time_signature', 'track_popularity', 'speechiness', 'danceability',
       'playlist_name', 'artist_name', 'duration_ms', 'energy',
       'playlist_genre', 'playlist_subgenre', 'track_name', 'mode',
       'track_album_release_date', 'instrumentalness', 'valence', 'tempo',
       'loudness', 'acousticness', 'liveness', 'track_album_name'],
      dtype='object')

In [460]:
spotify['track_album_release_date'] = pd.to_datetime(spotify['track_album_release_date'], format='mixed')           # it convert track album relase date into datatime64[ns] datatype

In [461]:
spotify.dtypes          # Check data types

time_signature                     float64
track_popularity                     int64
speechiness                        float64
danceability                       float64
playlist_name                       object
artist_name                         object
duration_ms                        float64
energy                             float64
playlist_genre                      object
playlist_subgenre                   object
track_name                          object
mode                               float64
track_album_release_date    datetime64[ns]
instrumentalness                   float64
valence                            float64
tempo                              float64
loudness                           float64
acousticness                       float64
liveness                           float64
track_album_name                    object
dtype: object

In [462]:
spotify.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3144 entries, 0 to 3144
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time_signature            3144 non-null   float64
 1   track_popularity          3144 non-null   int64
 2   speechiness               3144 non-null   float64
 3   danceability              3144 non-null   float64
 4   playlist_name             3144 non-null   object
 5   artist_name               3144 non-null   object
 6   duration_ms               3144 non-null   float64
 7   energy                    3144 non-null   float64
 8   playlist_genre            3144 non-null   object
 9   playlist_subgenre         3144 non-null   object
 10  track_name                3144 non-null   object
 11  mode                      3144 non-null   float64
 12  track_album_release_date  3144 non-null   datetime64[ns]
 13  instrumentalness          3144 non-null   float64
 14  valence                   3144 non-null   float64
 15  tempo                     3144 non-null   float64
 16  loudness                  3144 non-null   float64
 17  acousticness              3144 non-null   float64
 18  liveness                  3144 non-null   float64
 19  track_album_name          3144 non-null   object
dtypes: datetime64[ns](1), float64(12), int64(1), object(6)
memory usage: 515.8+ KB

In [463]:
spotify.isnull().sum()

time_signature              0
track_popularity            0
speechiness                 0
danceability                0
playlist_name               0
artist_name                 0
duration_ms                 0
energy                      0
playlist_genre              0
playlist_subgenre           0
track_name                  0
mode                        0
track_album_release_date    0
instrumentalness            0
valence                     0
tempo                       0
loudness                    0
acousticness                0
liveness                    0
track_album_name            0
dtype: int64

In [464]:
spotify.duplicated().sum()      # zero duplicates

np.int64(0)

In [487]:
spotify.rename(columns={'track_artist' : 'artist_name'}, inplace=True)  #Rename columns

In [488]:
spotify.shape           # no. or columns and rows

(3144, 20)

In [489]:
spotify.describe()

,time_signature,track_popularity,speechiness,danceability,duration_ms,energy,mode,track_album_release_date,instrumentalness,valence,tempo,loudness,acousticness,liveness
count,3144.000000,3144.000000,3144.000000,3144.000000,3.144000e+03,3144.000000,3144.000000,3144,3144.000000,3144.000000,3144.000000,3144.000000,3144.000000,3144.000000
mean,3.929389,43.477099,0.102174,0.607268,2.016402e+05,0.543509,0.553435,2019-09-03 03:46:43.053435136,0.286603,0.458438,116.766884,-10.663833,0.405567,0.165487
min,1.000000,11.000000,0.021900,0.058900,3.537500e+04,0.000202,0.000000,1990-01-01 00:00:00,0.000000,0.029600,48.232000,-48.069000,0.000004,0.022000
25%,4.000000,32.000000,0.038800,0.509000,1.518962e+05,0.357750,0.000000,2019-02-13 00:00:00,0.000000,0.232000,94.889250,-11.999750,0.084100,0.096400
50%,4.000000,46.000000,0.055000,0.649500,1.846410e+05,0.592000,1.000000,2022-10-27 00:00:00,0.001060,0.462000,116.052000,-8.026000,0.316000,0.116000
75%,4.000000,55.000000,0.118000,0.753000,2.264302e+05,0.747000,1.000000,2024-03-13 00:00:00,0.788000,0.673000,136.706500,-5.831000,0.725250,0.189000
max,5.000000,68.000000,0.927000,0.977000,1.355260e+06,0.998000,1.000000,2024-11-22 00:00:00,0.991000,0.987000,241.426000,1.318000,0.996000,0.979000
std,0.447827,14.823668,0.101726,0.200372,9.157390e+04,0.263635,0.497216,NaN,0.395181,0.266140,29.152400,8.155066,0.342249,0.124652

## Exploratory Data Analysis (EDA)

Exploratory Data Analysis was performed using Pandas to identify patterns, trends, and relationships within the Spotify dataset.

The analysis focused on:
- Most popular songs
- Least popular songs
- Top artists by popularity
- Genre-wise energy analysis
- Genre-wise danceability analysis
- Album popularity analysis
- Correlation between audio features

### Top 10 Most Popular Songs

In [493]:
# Find Top 10 Most Popular Songs   
spotify[['track_name', 'artist_name', 'track_popularity']].sort_values(by='track_popularity', ascending=False).head(10)

,track_name,artist_name,track_popularity
482,Can I Kick It?,A Tribe Called Quest,68
481,Survival of the Fittest,Mobb Deep,68
425,OZEBA,Rema,68
2532,Fotografía,"Juanes, Nelly Furtado",68
2663,Djadja,Aya Nakamura,68
31,"Sonata No. 14 ""Moonlight"" in C-Sharp Minor"", O...","Ludwig van Beethoven, Paul Lewis",68
516,MAMI WATA,"Gazo, Tiakola",68
102,Bandoleros,"Don Omar, Tego Calderón",68
1578,Kafamın İçi,"Ebru Yaşar, Siyam, Zeyd",68
489,Keep Ya Head Up,2Pac,68

### Top 10 Least Popular Songs

In [494]:
 # Find least 10 most popular songs 
spotify[['track_name','artist_name','track_popularity']].sort_values(by='track_popularity', ascending=False).reset_index().tail(10)

,index,track_name,artist_name,track_popularity
3134,2626,Ein yeush,"Moshe Lang, A.Y. Bouzaglou",11
3135,2829,Sand Castle,Taisen,11
3136,1346,La Sabrosona,Fito Olivares,11
3137,462,2 BOLD,Jomega,11
3138,3102,It Ain't You,Hedda Mae,11
3139,1196,Covered By The Clouds,NSH,11
3140,3113,All About The Games - Official Swedish Song Fo...,John Lundvik,11
3141,2542,Half Breed - Remix,DJ Shub,11
3142,2634,Elokai,"Eli Skies, Dovid Gross",11
3143,3099,Distant,Hanne Mjøen,11

## Top artists by popularity

In [512]:
spotify.groupby('artist_name')['track_popularity'].mean().sort_values(ascending=False).head(10).reset_index()

                                         artist_name  track_popularity
0                           James Mac, Vall, Rosalie              68.0
1                              Ayo Maff, Fireboy DML              68.0
2            The Blessed Madonna, Clementine Douglas              68.0
3                                               Korn              68.0
4                            Don Omar, Tego Calderón              68.0
5                                   Alok, Bebe Rexha              68.0
6                                        Teto, Matuê              68.0
7          Jasleen Royal, B Praak, Romy, Anvita Dutt              68.0
8  Purple Disco Machine, Benjamin Ingrosso, Nile ...              68.0
9                                    Crystal Castles              68.0

This analysis identifies the artists with the highest average popularity scores in the dataset.

## Top 10 least artist

In [519]:
# Bottom 10 artists appear in the dataset.
spotify['artist_name'].value_counts().tail(10).reset_index()

                    artist_name  count
0    Brian Simpson, Peter White      1
1                  Delorme & Co      1
2  Adam Hawley, Marcus Anderson      1
3                        Ny Cic      1
4    Dave Koz, Brian Culbertson      1
5                    Steve Cole      1
6                 Gregg Karukas      1
7                         Oaty.      1
8            Saiko, Joe Sunrise      1
9              Sudha Ragunathan      1

This analysis identifies the artists with the least average popularity scores in the dataset.

## Top 10 Genre-wise energy analysis

In [530]:
# Which genres are most energetic and intense.
spotify.groupby('playlist_genre')['energy'].mean().sort_values(ascending=False).reset_index().head(10)

  playlist_genre    energy
0          metal  0.928500
1           soca  0.853857
2          j-pop  0.832250
3           funk  0.808714
4           punk  0.796875
5          k-pop  0.744500
6           rock  0.741673
7         gospel  0.717205
8         indian  0.712708
9        turkish  0.707703

This analysis shows which music genres have the highest average energy levels.

## Top 10 Genre-wise danceability analysis

In [514]:
# Which music genres are most danceable on average.
spotify.groupby('playlist_genre')['danceability'].mean().sort_values(ascending=False).head(10).reset_index()

  playlist_genre  danceability
0           soca      0.794929
1      afrobeats      0.756742
2        hip-hop      0.755530
3          disco      0.746000
4         reggae      0.738895
5          k-pop      0.726333
6          latin      0.721564
7      brazilian      0.721134
8           funk      0.709821
9        turkish      0.688406

This analysis identifies which music genres are most danceable on average.

## Album popularity analysis

In [531]:
spotify.groupby('track_album_name')['track_popularity'].mean().sort_values(ascending=False).head(10).reset_index()

                            track_album_name  track_popularity
0                                       Korn              68.0
1                                  The Viper              68.0
2                                     Baller              68.0
3                    41 World: Not The Album              68.0
4                       Me Against The World              68.0
5            Me Acostumbre (feat. Bad Bunny)              68.0
6                                 Hold On Me              68.0
7  Honey Boy (feat. Nile Rodgers & Shenseea)              68.0
8                          Deep In Your Love              68.0
9                                         M4              68.0

This analysis highlights the albums with the highest average popularity scores.

## Top 10 Artist

In [515]:
# Top 10 artist appear most frequently in the dataset.
spotify['artist_name'].value_counts().head(10).reset_index()

   artist_name  count
0     Ren Avel     26
1        Asake     19
2         Bnxn     19
3  LoFi Waiter     18
4   Seyi Vibez     18
5       Wizkid     14
6    Burna Boy     11
7   Zinoleesky     11
8    Bad Bunny     10
9    Yume.Play     10

These analysis highlights top 10 artist from the dataset

## Top 10 Albums by Popularity

In [517]:
# Top 10 albums 
spotify.groupby('track_album_name')['track_popularity'].mean().sort_values(ascending=False).head(10).reset_index()

                            track_album_name  track_popularity
0                                       Korn              68.0
1                                  The Viper              68.0
2                                     Baller              68.0
3                    41 World: Not The Album              68.0
4                       Me Against The World              68.0
5            Me Acostumbre (feat. Bad Bunny)              68.0
6                                 Hold On Me              68.0
7  Honey Boy (feat. Nile Rodgers & Shenseea)              68.0
8                          Deep In Your Love              68.0
9                                         M4              68.0

This analysis identifies the top 10 albums with the highest average popularity in the dataset.

## Number of genre present in data

In [523]:
# no. of genre present in data and which genre appeared most
spotify['playlist_genre'].value_counts().reset_index()

   playlist_genre  count
0      electronic    441
1         ambient    298
2            lofi    296
3           latin    241
4           world    224
5         hip-hop    168
6          arabic    158
7             pop    158
8            jazz    145
9       brazilian    134
10      classical    111
11           rock    110
12       wellness     80
13        turkish     64
14      afrobeats     62
15         indian     48
16          blues     43
17           soul     42
18         gospel     39
19           folk     35
20         gaming     33
21           funk     28
22       cantopop     27
23         korean     26
24           punk     24
25         reggae     19
26          metal     14
27       mandopop     14
28           soca     14
29          indie     13
30          j-pop     12
31          disco      9
32        country      8
33          k-pop      6

This analysis show the number of genre present in the dataset.

## Top 10 genre by popularity

In [522]:
# Which music genre has the highest average popularity.
spotify.groupby('playlist_genre')['track_popularity'].mean().sort_values(ascending=False).reset_index().head(10)

  playlist_genre  track_popularity
0         korean         59.769231
1          metal         59.071429
2          j-pop         58.833333
3          indie         58.307692
4          k-pop         56.500000
5         reggae         55.578947
6       mandopop         53.785714
7           punk         52.625000
8           soul         51.619048
9       wellness         49.512500

This analysis shows the top 10 genre by popularity.

## Top 10 Genre for Dance

In [525]:
# Which genres are most suitable for dancing.
spotify.groupby('playlist_genre')['danceability'].mean().sort_values(ascending=False).reset_index().head(10)

  playlist_genre  danceability
0           soca      0.794929
1      afrobeats      0.756742
2        hip-hop      0.755530
3          disco      0.746000
4         reggae      0.738895
5          k-pop      0.726333
6          latin      0.721564
7      brazilian      0.721134
8           funk      0.709821
9        turkish      0.688406

This analysis shows top 10 genre for best for Dance.

## Correlation between columns

In [526]:
spotify.corr(numeric_only=True)         # How strongly numeric columns are related to each other.

,time_signature,track_popularity,speechiness,danceability,duration_ms,energy,mode,instrumentalness,valence,tempo,loudness,acousticness,liveness
time_signature,1.000000,-0.010980,0.114529,0.214755,-0.018357,0.197434,-0.014485,-0.152272,0.147973,-0.004473,0.227182,-0.193676,0.031137
track_popularity,-0.010980,1.000000,0.078149,0.083806,-0.058848,0.017646,-0.034843,-0.003918,0.001621,0.004540,0.012829,-0.041779,0.007539
speechiness,0.114529,0.078149,1.000000,0.264389,-0.089258,0.196815,-0.089891,-0.265247,0.234234,0.063185,0.222619,-0.153281,0.125471
danceability,0.214755,0.083806,0.264389,1.000000,-0.126121,0.479996,-0.132830,-0.383261,0.567711,0.060385,0.628247,-0.442346,0.034756
duration_ms,-0.018357,-0.058848,-0.089258,-0.126121,1.000000,0.126950,0.034127,-0.134528,-0.032379,0.045749,0.067306,-0.114682,0.008820
energy,0.197434,0.017646,0.196815,0.479996,0.126950,1.000000,-0.095589,-0.603950,0.533824,0.213233,0.815123,-0.769601,0.211363
mode,-0.014485,-0.034843,-0.089891,-0.132830,0.034127,-0.095589,1.000000,0.054187,-0.089339,-0.012821,-0.133522,0.068399,-0.023883
instrumentalness,-0.152272,-0.003918,-0.265247,-0.383261,-0.134528,-0.603950,0.054187,1.000000,-0.486240,-0.133224,-0.631046,0.525254,-0.142386
valence,0.147973,0.001621,0.234234,0.567711,-0.032379,0.533824,-0.089339,-0.486240,1.000000,0.114126,0.524610,-0.389790,0.074047
tempo,-0.004473,0.004540,0.063185,0.060385,0.045749,0.213233,-0.012821,-0.133224,0.114126,1.000000,0.174801,-0.171068,0.073423
loudness,0.227182,0.012829,0.222619,0.628247,0.067306,0.815123,-0.133522,-0.631046,0.524610,0.174801,1.000000,-0.657030,0.175084
acousticness,-0.193676,-0.041779,-0.153281,-0.442346,-0.114682,-0.769601,0.068399,0.525254,-0.389790,-0.171068,-0.657030,1.000000,-0.159900
liveness,0.031137,0.007539,0.125471,0.034756,0.008820,0.211363,-0.023883,-0.142386,0.074047,0.073423,0.175084,-0.159900,1.000000

## Top 10 genre with the most positive / happy emotional vibe.

In [529]:
# Top 10 genres have the most positive/happy emotional vibe.
spotify.groupby('playlist_genre')['valence'].mean().sort_values(ascending=False).reset_index().head(10)

  playlist_genre   valence
0      brazilian  0.752239
1         reggae  0.739000
2           soca  0.730786
3          k-pop  0.726333
4          disco  0.704778
5           funk  0.644643
6          indie  0.632538
7           punk  0.603942
8        country  0.597250
9        hip-hop  0.586017

## Key Insights

- Energetic songs are generally louder.
- Danceable songs tend to have more positive emotional tones.
- Acoustic songs are usually less energetic.
- Instrumental songs often have lower loudness.
- Popularity does not strongly depend on audio features alone.

## Conclusion

This project analyzed Spotify music data using Pandas to identify trends related to song popularity, genres, artists, and audio features. The analysis helped understand relationships between musical characteristics such as energy, loudness, danceability, and acousticness.